# permissions for end users to view orchestrators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: orchestrator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orchestrator
    app.kubernetes.io/part-of: orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: orchestrator-viewer-role
rules:
- apiGroups:
  - parodos.dev.parodos.dev
  resources:
  - orchestrators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - parodos.dev.parodos.dev
  resources:
  - orchestrators/status
  verbs:
  - get
