apiVersion: parodos.dev.parodos.dev/v1alpha1
kind: Orchestrator
metadata:
  name: orchestrator-sample
spec:
  # Default values copied from <project_dir>/helm-charts/orchestrator/values.yaml
  backstage:
    global:
      dynamic:
        includes:
        - dynamic-plugins.default.yaml
        plugins:
        - disabled: false
          integrity: sha512-/ZQZI6bssyYT1D2+LW/pqpdIFJJXCW5RC0Ti49YdyminEbAYmjhjKxEHagKRaxwYhmCHbJezkuqrUAern/xcbA==
          package: '@janus-idp/backstage-plugin-orchestrator-backend-dynamic@1.2.0'
          pluginConfig:
            orchestrator:
              dataIndexService:
                url: http://sonataflow-platform-data-index-service.sonataflow-infra
              editor:
                path: https://sandbox.kie.org/swf-chrome-extension/0.32.0
        - disabled: false
          integrity: sha512-RjtUkE1JxzEQhFGgpEW3yCtdLTf6B+FvNAVhWC6xkETk7BwGz+RO8CeDUVyXwuf6OJg1w347gZIjV64naqA+UA==
          package: '@janus-idp/backstage-plugin-orchestrator@1.3.0'
          pluginConfig:
            dynamicPlugins:
              frontend:
                janus-idp.backstage-plugin-orchestrator:
                  appIcons:
                  - importName: OrchestratorIcon
                    module: OrchestratorPlugin
                    name: orchestratorIcon
                  dynamicRoutes:
                  - importName: OrchestratorPage
                    menuItem:
                      icon: orchestratorIcon
                      text: Orchestrator
                    module: OrchestratorPlugin
                    path: /orchestrator
        - disabled: false
          package: ./dynamic-plugins/dist/janus-idp-plugin-notifications
          pluginConfig:
            dynamicPlugins:
              frontend:
                janus-idp.backstage-plugin-notifications:
                  appIcons:
                  - importName: NotificationsActiveIcon
                    module: NotificationsPlugin
                    name: notificationsIcon
                  dynamicRoutes:
                  - config:
                      pollingIntervalMs: 5000
                    importName: NotificationsPage
                    menuItem:
                      icon: notificationsIcon
                      text: Notifications
                    module: NotificationsPlugin
                    path: /notifications
        - disabled: false
          package: ./dynamic-plugins/dist/janus-idp-plugin-notifications-backend-dynamic
    upstream:
      backstage:
        appConfig:
          auth:
            environment: development
            providers:
              github:
                development:
                  clientId: INSERT VALID CLIENT ID HERE
                  clientSecret: INSERT VALID CLIENT SECRET HERE
          backend:
            csp:
              frame-src:
              - https://sandbox.kie.org
            database:
              client: pg
              connection:
                host: orchestrator-postgresql-hl.orchestrator.svc.cluster.local
                password: ${POSTGRESQL_ADMIN_PASSWORD}
                port: 5432
                user: postgres
          catalog:
            locations:
            - target: https://github.com/janus-idp/backstage-plugins/blob/main/plugins/notifications-backend/users.yaml
              type: url
            - target: https://github.com/parodos-dev/workflow-software-templates/blob/main/entities/workflow-resources.yaml
              type: url
            - target: https://github.com/parodos-dev/workflow-software-templates/blob/main/template/infrastructure/template.yaml
              type: url
            - target: https://github.com/parodos-dev/workflow-software-templates/blob/main/template/assessment/template.yaml
              type: url
            - target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
              type: url
            rules:
            - allow:
              - Component
              - System
              - Group
              - Resource
              - Location
              - Template
              - API
              - User
              - Domain
          integrations:
            github:
            - host: github.com
              token: INSERT VALID TOKEN HERE
        image:
          tag: pr-896
  orchestrator:
    devmode: false
    namespace: sonataflow-infra
    sonataPlatform:
      dataIndex:
        image: quay.io/kiegroup/kogito-data-index-postgresql-nightly:latest
      jobService:
        image: quay.io/kiegroup/kogito-jobs-service-postgresql-nightly:latest
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 64Mi
    sonataflows:
    - image: quay.io/orchestrator/serverless-workflow-greeting:latest
      name: greeting
  postgres:
    authSecret:
      name: sonataflow-psql-postgresql
      passwordKey: postgres-password
      userKey: postgres-username
    database: sonataflow
    serviceName: sonataflow-psql-postgresql
    serviceNamespace: sonataflow-infra
  serverlessOperator:
    enabled: true
    subscription:
      channel: stable
      installPlanApproval: Automatic
      namespace: openshift-serverless
      pkgName: serverless-operator
      sourceNamespace: openshift-marketplace
  sonataFlowOperator:
    enabled: true
    subscription:
      channel: alpha
      installPlanApproval: Automatic
      namespace: openshift-operators
      pkgName: sonataflow-operator
      source: sonataflow-operator
      sourceImage: quay.io/masayag/kogito-serverless-operator-catalog:v2.0.0-snapshot
      sourceNamespace: openshift-marketplace
  
  
