apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: backstage
  repository: https://janus-idp.github.io/helm-backstage
  version: 2.12.5
description: 'Helm chart to deploy the Orchestrator solution suite on OpenShift, including
  Janus IDP backstage, SonataFlow Operator, OpenShift Serverless Operator, Knative
  Eventing and Knative Serving. '
icon: https://raw.githubusercontent.com/parodos-dev/parodos-dev.github.io/main/assets/images/WO_black.svg
name: orchestrator
type: application
version: 0.1.21
